services:
  corewebapi:
    container_name: corewebapi
    image: corewebapi
    build:
      context: .
      dockerfile: CoreWebApi/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__SqlServerConnection=${CONNECTIONSTRINGS__SQLSERVERCONNECTION}
    networks:
      - mynetwork
    ports:
      - "8080:8080"
    depends_on:
      - sql_server_container

  sql_server_container:
    platform: linux/amd64
    container_name: sql_server_container
    image: mcr.microsoft.com/mssql/server:latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${MSSQL_SA_PASSWORD}
    volumes:
      - mssql_data:/var/opt/mssql 
    networks:
      - mynetwork
    ports:
      - "1433:1433"

volumes:
  mssql_data:
networks:
  mynetwork:
